# Generated by Django 5.1.4 on 2025-01-18 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('users', '0002_alter_user_options_remove_user_username_user_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pay', models.DateTimeField(auto_now=True, help_text='Дата и время совершения оплаты.', verbose_name='Дата оплаты')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма, которую заплатил пользователь.', max_digits=10, verbose_name='Сумма оплаты')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод')], default='cash', help_text='Способ, с помощью которого была произведена оплата.', max_length=10, verbose_name='Способ оплаты')),
                ('pay_course', models.ForeignKey(blank=True, help_text='Курс, за который была произведена оплата.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_for_course', to='materials.course', verbose_name='Оплаченный курс')),
                ('pay_lesson', models.ForeignKey(blank=True, help_text='Урок, за который была произведена оплата.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_for_lesson', to='materials.lesson', verbose_name='Оплаченный урок')),
                ('user', models.ForeignKey(help_text='Пользователь, который осуществил покупку.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
