# Generated by Django 5.1.4 on 2025-01-25 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_pay'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
