# Generated by Django 5.1.4 on 2025-02-14 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_lesson_amount'),
        ('users', '0003_pay'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pay', models.DateTimeField(auto_now=True, help_text='Дата и время совершения оплаты.', verbose_name='Дата оплаты')),
                ('amount', models.DecimalField(decimal_places=2, default=1, help_text='Сумма, которую заплатил пользователь.', max_digits=10, verbose_name='Сумма оплаты')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод')], default='cash', help_text='Способ, с помощью которого была произведена оплата.', max_length=10, verbose_name='Способ оплаты')),
                ('session_id', models.CharField(blank=True, help_text='Укажите id сессии', max_length=255, null=True, verbose_name='ID сессии')),
                ('link', models.URLField(blank=True, help_text='Укажите ссылку на оплату', max_length=400, null=True, verbose_name='Ссылка на оплату')),
                ('pay_course', models.ForeignKey(blank=True, help_text='Курс, за который была произведена оплата.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_for_course', to='materials.course', verbose_name='Оплаченный курс')),
                ('pay_lesson', models.ForeignKey(blank=True, help_text='Урок, за который была произведена оплата.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_for_lesson', to='materials.lesson', verbose_name='Оплаченный урок')),
                ('user', models.ForeignKey(help_text='Пользователь, который осуществил покупку.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплата',
            },
        ),
        migrations.DeleteModel(
            name='Pay',
        ),
    ]
