# Generated by Django 5.1.4 on 2025-02-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='link',
            field=models.URLField(blank=True, help_text='Укажите ссылку на оплату', max_length=400, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='pay',
            name='session_id',
            field=models.CharField(blank=True, help_text='Укажите id сессии', max_length=255, null=True, verbose_name='ID сессии'),
        ),
    ]
