version: "3.9"

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:16.0
    volumes:
      - postgres_data:/var/lib/postgres/data
    env_file:
      - ./.env

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A config worker
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery_beat:
    build: .
    command: celery -A your_project_name beat
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
  static_volume:
