version: "3.8"

networks:
  my_django_network:
    name: my_django_network

services:
  nginx:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - web
    networks:
      - my_django_network

  web:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "python3", "manage.py", "migrate"]
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - localhost
      - redis
    env_file:
      - .env
    networks:
      - my_django_network

  db:
    image: postgres:16.0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - my_django_network

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    networks:
      - my_django_network

# Прокомментированные сервисы для Celery, если они понадобятся позже:
#  celery:
#    build: .
#    command: celery -A config worker
#    depends_on:
#      - db
#      - redis
#    env_file:
#      - .env
#    networks:
#      - my_django_network

#  celery_beat:
#    build: .
#    command: celery -A your_project_name beat
#    depends_on:
#      - db
#      - redis
#    env_file:
#     - .env
#    networks:
#      - my_django_network

volumes:
  postgres_data:
  static_volume: