# Generated by Django 5.1.4 on 2025-01-10 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название курса.', max_length=150, verbose_name='Название')),
                ('image', models.ImageField(blank=True, help_text='Прикрепите изображение для превью.', null=True, upload_to='images_course/', verbose_name='Изображение (превью)')),
                ('description', models.TextField(help_text='Добавьте подробное описание курса.', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название урока.', max_length=150, verbose_name='Название')),
                ('image', models.ImageField(blank=True, help_text='Прикрепите изображение для превью.', null=True, upload_to='images_course/', verbose_name='Изображение (превью)')),
                ('description', models.TextField(help_text='Добавьте описание урока.', verbose_name='Описание')),
                ('course', models.ForeignKey(help_text='Укажите, к какому курсу относится этот урок.', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='materials.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
