# Generated by Django 5.1.4 on 2025-02-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Добавьте подробное описание курса.', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, help_text='Добавьте описание урока.', null=True, verbose_name='Описание'),
        ),
    ]
