# Generated by Django 5.1.4 on 2025-02-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_course_description_alter_lesson_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.IntegerField(default=1, help_text='Укажите цену в рублях', verbose_name='Цена'),
        ),
    ]
