# Generated by Django 5.1.4 on 2025-02-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_lesson_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_updated_course',
            field=models.DateTimeField(auto_now=True, verbose_name='дата Последнего обновление'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='last_updated_lesson',
            field=models.DateTimeField(auto_now=True, verbose_name='дата Последнего обновление'),
        ),
    ]
